config/routes.rb
require "sidekiq/web"
Sidekiq::Web.app_url = "/"

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  mount Sidekiq::Web => '/sidekiq'
  namespace :admin do
    get '/sign_in', to: "sign_ins#new", as: :admin_sign_in
    resource :sign_ins, only: [:create, :destroy]
    resources :product_urls, except: [:index]
  end

  authenticated :user do
    root 'product_urls#index', as: :user_root
  end
  root 'home#index'
  resources :home, only: [:show]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_product_url, only: [:show]

  def index
    @partner    = Partner.find_by(name: 'Flipkart')
    @categories = set_categories
    @products   = set_products
  end

  def show

  end

  private

  def set_product_url
    @product_url = ProductUrl.find_by(id: params[:id])
    return if @product_url.present?
    flash[:error] = 'Product is not found'
    redirect_back(fallback_location: root_path)
  end

  def set_categories
    @partner
      .product_urls
      .where(scraping_status: "success")
      .where("parsed_data->>'breadcrumb' is not null")
      .select(Arel.sql("parsed_data->>'breadcrumb' as category_name, count(id) as product_count"))
      .group('1')
      .map do |category|
      begin
        {
          name:  JSON.parse(category['category_name'])[1],
          count: category['product_count']
        }
      rescue
        nil
      end
    end.compact_blank
      .uniq
      .group_by { |i| i[:name] }
      .transform_values { |v| v.pluck(:count).sum }
      .sort_by { |k, v| }
      .reverse
      .first(4)
      .to_h
  end

  def set_products
    @partner
      .product_urls
      .where(scraping_status: "success")
      .order(created_at: :desc)
      .limit(10)
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def pluralize_category(product_count)
    [
      product_count,
      "Product".pluralize(product_count),
      "available"
    ].join(' ')
  end
end

app/views/home/components/_category_item.html.erb
<div class="w-full px-4 sm:w-1/2 lg:w-1/4">
  <a href="javascript:void(0)" class="group mb-10 block text-center">
    <div class="mb-5 overflow-hidden rounded-lg">
      <%= image_tag('category-item', alt: "category", class: "w-full") %>
    </div>
    <h3 class="mb-1 text-xl font-semibold text-black group-hover:text-primary md:text-2xl lg:text-xl xl:text-2xl">
      <!--  Category name-->
      <%= category_name %>
    </h3>
    <p class="text-base font-medium text-body-color">
      <!--  Product count -->
      <%= pluralize_category(product_count) %>
    </p>
  </a>
</div>

app/views/home/components/_product_carousel_item.html.erb
<div class="mx-auto h-full min-w-[300px] px-4 xs:min-w-[368px] sm:min-w-[510px] md:min-w-[340px] lg:min-w-[312px] xl:min-w-[282px] 2xl:min-w-[325px]" title="<%= product.parsed_data['name'] %>">
  <div class="mb-10 overflow-hidden rounded-lg bg-white shadow-card">
    <div class="relative">
      <% if product.product_images.attached? && product.product_images.first.present? %>
        <%= image_tag(rails_blob_url(product.product_images.first), alt: "product", class: "w-full", style: 'height: 200px;width: 70%;position: relative;left: 10%;') %>
      <% end %>
      <span class="absolute left-5 top-5 inline-flex items-center justify-center rounded bg-red-600 px-3 py-1 text-sm font-semibold text-white">Hot</span>
    </div>
    <div class="px-5 pt-6 pb-8 text-center">
      <h3>
        <!--        Product link-->
        <%= link_to home_path(product), class: 'text-lg font-semibold text-black hover:text-primary xs:text-xl' do %>
          <%= product.parsed_data['name'].to_s.truncate(30) %>
        <% end %>
      </h3>
      <p class="text-lg font-semibold text-black">Price: <%= comma_style(product.parsed_data['price'].to_f, precision: 0) %></p>
      <p class="text-lg font-semibold text-black">Rating: <%= product.parsed_data['avg_rating'] %></p>
      <div class="text-center">
        <%= link_to home_path(product), class: 'inline-flex items-center justify-center rounded-md bg-primary py-3 px-8 text-center text-base font-semibold text-white hover:bg-black' do %>
          View Product
        <% end %>
      </div>
    </div>
  </div>
</div>