config/routes.rb
require "sidekiq/web"
Sidekiq::Web.app_url = "/"

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  mount Sidekiq::Web => '/sidekiq'
  namespace :admin do
    get '/sign_in', to: "sign_ins#new", as: :admin_sign_in
    resource :sign_ins, only: [:create, :destroy]
    resources :product_urls, except: [:index]
  end

  authenticated :user do
    root 'product_urls#index', as: :user_root
  end
  root 'home#index'
  resources :home, only: [:show]
end

app/views/shared/_footer.html.erb
<footer class="bg-white">
  <div class="pt-[70px]">
    <div class="container mx-auto">
      <div class="-mx-4 flex flex-wrap">
        <div class="w-full px-4 md:w-1/2 lg:w-5/12 xl:w-4/12">
          <div class="mb-16 max-w-[270px]">
            <%= link_to root_path, class: 'mb-8 inline-block' do %>
              <%= image_tag('aladdin-logo', alt: "logo", class: "max-w-full", style: 'height: 50px;width: 50px;') %>
            <% end %>

            <div class="space-y-4">
              <p class="flex text-base font-medium text-body-color">
                <span class="pr-4">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M20.1818 22H15.7987C14.8247 22 14.013 21.188 14.013 20.2136V16.6407C14.013 16.2834 13.7208 15.9911 13.3636 15.9911H10.6688C10.3117 15.9911 10.0195 16.2834 10.0195 16.6407V20.1811C10.0195 21.1555 9.20779 21.9675 8.23377 21.9675H3.78571C2.81169 21.9675 2 21.1555 2 20.1811V8.84531C2 8.3581 2.25974 7.90337 2.68182 7.64352L11.2532 2.21924C11.7078 1.92692 12.3247 1.92692 12.7792 2.21924L21.3506 7.64352C21.7727 7.90337 22 8.3581 22 8.84531V20.1486C22 21.188 21.1883 22 20.1818 22ZM10.6364 14.8542H13.3312C14.3052 14.8542 15.1169 15.6663 15.1169 16.6407V20.1811C15.1169 20.5384 15.4091 20.8307 15.7662 20.8307H20.1818C20.539 20.8307 20.8312 20.5384 20.8312 20.1811V8.87779C20.8312 8.78035 20.7662 8.68291 20.7013 8.61795L12.1623 3.19367C12.0649 3.1287 11.9351 3.1287 11.8701 3.19367L3.2987 8.61795C3.2013 8.68291 3.16883 8.78035 3.16883 8.87779V20.2136C3.16883 20.5708 3.46104 20.8632 3.81818 20.8632H8.23377C8.59091 20.8632 8.88312 20.5708 8.88312 20.2136V16.6407C8.85065 15.6663 9.66234 14.8542 10.6364 14.8542Z" fill="#3056D3"></path>
                  </svg>
                </span>

                <span> Shop 009A, Level 4, Block A, Demo Park, Ottawa </span>
              </p>
              <p class="flex text-base font-medium text-body-color">
                <span class="pr-4">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M21.2402 13.7615C21.1683 12.9346 20.4852 12.3594 19.6584 12.3594H4.34301C3.51613 12.3594 2.869 12.9706 2.76114 13.7615L2.00616 21.3113C1.97021 21.7427 2.11402 22.2101 2.40163 22.5337C2.68924 22.8572 3.12066 23.037 3.58803 23.037H20.4493C20.8807 23.037 21.3121 22.8572 21.6357 22.5337C21.9233 22.2101 22.0671 21.7787 22.0312 21.3113L21.2402 13.7615ZM20.665 21.7068C20.629 21.7427 20.5571 21.8146 20.4133 21.8146H3.58803C3.48017 21.8146 3.37232 21.7427 3.33637 21.7068C3.30042 21.6708 3.22851 21.5989 3.26446 21.4551L4.01945 13.8693C4.01945 13.6896 4.16325 13.5817 4.34301 13.5817H19.6943C19.8741 13.5817 19.9819 13.6896 20.0179 13.8693L20.7729 21.4551C20.7369 21.563 20.7009 21.6708 20.665 21.7068Z" fill="#3056D3"></path>
                    <path d="M12.0007 15.166C10.5986 15.166 9.48413 16.2805 9.48413 17.6826C9.48413 19.0847 10.5986 20.1992 12.0007 20.1992C13.4028 20.1992 14.5173 19.0847 14.5173 17.6826C14.5173 16.2805 13.4028 15.166 12.0007 15.166ZM12.0007 18.9409C11.3177 18.9409 10.7424 18.3657 10.7424 17.6826C10.7424 16.9995 11.3177 16.4243 12.0007 16.4243C12.6838 16.4243 13.259 16.9995 13.259 17.6826C13.259 18.3657 12.6838 18.9409 12.0007 18.9409Z" fill="#3056D3"></path>
                    <path d="M2.86896 7.54318C2.94086 9.12504 4.34297 9.77217 5.062 9.77217H7.57861C7.61456 9.77217 7.61456 9.77217 7.61456 9.77217C8.6931 9.70027 9.77165 8.98124 9.77165 7.54318V6.68034C10.958 6.68034 13.6904 6.68034 14.8768 6.68034V7.54318C14.8768 8.98124 15.9553 9.70027 17.0339 9.77217H17.0698H19.5505C20.2695 9.77217 21.6716 9.12504 21.7435 7.54318C21.7435 7.43532 21.7435 7.03985 21.7435 6.68034C21.7435 6.39273 21.7435 6.14107 21.7435 6.10511C21.7435 6.06916 21.7435 6.03321 21.7435 6.03321C21.6357 5.02657 21.2761 4.19968 20.665 3.55256L20.629 3.51661C19.7302 2.68972 18.6517 2.22235 17.8248 1.93474C15.416 1 12.3961 1 12.2523 1C10.1312 1.03595 8.76501 1.21571 6.71577 1.93474C5.92484 2.1864 4.84629 2.65377 3.9475 3.48065L3.91155 3.51661C3.30038 4.16373 2.94086 4.99062 2.83301 5.99726C2.83301 6.03321 2.83301 6.06916 2.83301 6.06916C2.83301 6.14107 2.83301 6.35678 2.83301 6.64439C2.86896 6.96795 2.86896 7.39937 2.86896 7.54318ZM4.81034 4.37944C5.52937 3.73232 6.42816 3.33685 7.18314 3.04924C9.05262 2.36616 10.275 2.22235 12.3242 2.1864C12.468 2.1864 15.2722 2.22235 17.4293 3.04924C18.1843 3.33685 19.0831 3.69636 19.8021 4.37944C20.1976 4.81086 20.4493 5.38608 20.5212 6.06916C20.5212 6.17702 20.5212 6.35678 20.5212 6.64439C20.5212 7.0039 20.5212 7.39937 20.5212 7.50722C20.4852 8.33411 19.6943 8.51387 19.5864 8.51387H17.1058C16.7462 8.47791 16.171 8.33411 16.171 7.54318V6.06916C16.171 5.78155 15.9913 5.56584 15.7396 5.45799C15.5239 5.38609 9.23238 5.38609 9.01667 5.45799C8.76501 5.52989 8.58525 5.78155 8.58525 6.06916V7.54318C8.58525 8.33411 8.01003 8.47791 7.65051 8.51387H5.16986C5.062 8.51387 4.27107 8.33411 4.23512 7.50722C4.23512 7.39937 4.23512 7.0039 4.23512 6.64439C4.23512 6.35678 4.23512 6.21297 4.23512 6.10511C4.16321 5.38609 4.41487 4.81086 4.81034 4.37944Z" fill="#3056D3"></path>
                  </svg>
                </span>

                <span> +1-613-555-0182 </span>
              </p>
              <p class="flex text-base font-medium text-body-color">
                <span class="pr-4">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M21.0227 4H3.97727C2.88636 4 2 4.98345 2 6.19385V17.8061C2 19.0165 2.88636 20 3.97727 20H21.0227C22.1136 20 23 19.0165 23 17.8061V6.19385C23 4.98345 22.1136 4 21.0227 4ZM21.0227 5.32388C21.1932 5.32388 21.3295 5.3617 21.4659 5.47518L12.9773 11.1868C12.6705 11.3759 12.3295 11.3759 12.0227 11.1868L3.53409 5.47518C3.67045 5.39953 3.80682 5.32388 3.97727 5.32388H21.0227ZM21.0227 18.6383H3.97727C3.56818 18.6383 3.19318 18.26 3.19318 17.7683V6.79905L11.375 12.3215C11.7159 12.5485 12.0909 12.6619 12.4659 12.6619C12.8409 12.6619 13.2159 12.5485 13.5568 12.3215L21.7386 6.79905V17.7683C21.8068 18.26 21.4318 18.6383 21.0227 18.6383Z" fill="#3056D3"></path>
                  </svg>
                </span>

                <span> contact@yourmail.com </span>
              </p>
            </div>
          </div>
        </div>
        <div class="w-full px-4 sm:w-1/2 md:w-1/2 lg:w-4/12 xl:w-3/12">
          <div class="mb-16">
            <h3 class="mb-9 text-2xl font-semibold text-black">
              Shop Departments
            </h3>

            <ul class="space-y-3">
              <li>
                <a href="javascript:void(0)" class="inline-block text-base font-medium text-body-color hover:text-primary">
                  Computers &amp; Accessories
                </a>
              </li>
              <li>
                <a href="javascript:void(0)" class="inline-block text-base font-medium text-body-color hover:text-primary">
                  Smartphones &amp; Tablets
                </a>
              </li>
              <li>
                <a href="javascript:void(0)" class="inline-block text-base font-medium text-body-color hover:text-primary">
                  TV, Video &amp; Audio
                </a>
              </li>
              <li>
                <a href="javascript:void(0)" class="inline-block text-base font-medium text-body-color hover:text-primary">
                  Cameras, Photo &amp; Video
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="border-t border-[#e7e7e7] py-7">
    <div class="container mx-auto">
      <div class="text-center">
        <p class="mb-5 text-base font-medium text-body-color">
          © 2024 Aladdin. All Rights Reserved.
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_login_page.html.erb
<%= provide(:main_class, '') %>
<div class="bg-[#F9FAFB] h-screen w-screen flex items-center">
  <div class="h-max mx-auto flex flex-col items-center">
    <img class="h-[40px] w-[47px] mb-5" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
    <h1 class="text-xl font-bold text-center pb-10">Sign in to your account</h1>
    <%= form_with url: admin_sign_ins_path, data: { remote: true } do |f| %>
      <div class="bg-white shadow-xl p-10 flex flex-col gap-4 text-sm">
        <div>
          <label class="text-gray-600 font-bold inline-block pb-2" for="email">Email / Phone number</label>
          <%= f.email_field :email, autofocus: true, class: 'border border-gray-400 focus:outline-slate-400 rounded-md w-full shadow-sm px-5 py-2', placeholder: "thiyagu@jaman.com" %>
        </div>
        <div>
          <label class="text-gray-600 font-bold inline-block pb-2" for="password">Password</label>
          <%= f.password_field :password, autocomplete: "off", class: 'border border-gray-400 focus:outline-slate-400 rounded-md w-full shadow-sm px-5 py-2', placeholder: "******" %>
        </div>
        <div class="flex">
          <div class="w-1/2">
            <%= f.text_field :remeber_me, type: 'checkbox' %>
            <label for="remeberMe">Remeber me</label>
          </div>
          <div class="w-1/2">
            <!--            <a class="font-bold text-blue-600" href="">Forgot password ?</a>-->
          </div>
        </div>
        <div>
          <input class="bg-[#4F46E5] w-full py-2 rounded-md text-white font-bold cursor-pointer hover:bg-[#181196]" type="submit" value="Login">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<header x-data="
        {
          navbarOpen: false,
          searchForm: false,
          wishlistOpen: false,
          cartOpen: false,
          submenuOpen: false,
          categories: false,
          categoryOne: true,
        }
      " class="w-full bg-white">
  <div class="hidden border-b border-[#e7e7e7] sm:block">
    <div class="container mx-auto">
      <div class="-mx-4 flex flex-wrap">
        <div class="w-full px-4 md:w-2/3 lg:w-1/2">
          <ul class="-mx-3 flex items-center">
            <li>
              <a href="javascript:void(0)" class="inline-block py-4 px-3 text-sm font-medium text-body-color hover:text-primary">
                About Us
              </a>
            </li>
            <li>
              <a href="javascript:void(0)" class="inline-block py-4 px-3 text-sm font-medium text-body-color hover:text-primary">
                Order Tracking
              </a>
            </li>
            <li>
              <a href="support.html" class="inline-block py-4 px-3 text-sm font-medium text-body-color hover:text-primary">
                Contact Us
              </a>
            </li>
            <li>
              <a href="javascript:void(0)" class="inline-block py-4 px-3 text-sm font-medium text-body-color hover:text-primary">
                FAQs
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="border-b border-[#e7e7e7]">
    <div class="container mx-auto">
      <div class="relative -mx-4 flex items-center justify-center sm:justify-between">
        <div class="w-60 max-w-full px-4 lg:w-48">
          <%= link_to root_path, class: 'block w-full py-5 lg:py-3' do %>
            <%= image_tag('aladdin-logo', alt: 'logo', style: 'height: 35px;width: 35px;') %>
          <% end %>
        </div>
        <div class="flex w-full items-center justify-end px-4 lg:justify-between">
          <div class="flex w-full items-center justify-between px-4">
            <div class="w-full">
              <button @click="navbarOpen = !navbarOpen" :class="navbarOpen &amp;&amp; 'navbarTogglerActive' " id="navbarToggler" class="absolute right-4 top-1/2 block -translate-y-1/2 rounded-lg px-3 py-[6px] ring-primary focus:ring-2 lg:hidden">
                <span class="relative my-[6px] block h-[2px] w-[30px] bg-body-color"></span>
                <span class="relative my-[6px] block h-[2px] w-[30px] bg-body-color"></span>
                <span class="relative my-[6px] block h-[2px] w-[30px] bg-body-color"></span>
              </button>
              <nav :class="!navbarOpen &amp;&amp; 'hidden' " id="navbarCollapse" class="absolute right-4 top-full w-full max-w-[250px] justify-center rounded-lg bg-white py-5 px-6 shadow lg:static lg:flex lg:w-full lg:max-w-full lg:justify-end lg:bg-transparent lg:py-0 lg:px-0 lg:shadow-none hidden">
                <ul class="blcok items-center lg:flex">
                  <% top_nav_header_links.each do |link| %>
                    <li>
                      <%= link_to link[:path], class: link[:class] do %>
                        <%= link[:name] %>
                      <% end %>
                    </li>
                  <% end %>
                </ul>
              </nav>
            </div>
          </div>
          <div class="hidden w-full items-center justify-end space-x-4 pr-[70px] sm:flex lg:pr-0">
            <%= render 'user_profile' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_notification.html.erb
<div data-controller="notification"
     class="transition transform duration-1000 fixed inset-0 flex items-end justify-center px-4 py-6 pointer-events-none sm:p-6 sm:pt-16 sm:items-start sm:justify-end z-50"
     data-transition-enter-from="opacity-0 translate-x-6"
     data-transition-enter-to="opacity-100 translate-x-0"
     data-transition-leave-from="opacity-100 translate-x-0"
     data-transition-leave-to="opacity-0 translate-x-6">
  <div class="max-w-sm w-full bg-white shadow-2xl pointer-events-auto rounded-lg  overflow-hidden p-4 z-50">
    <div class="flex items-start">

      <% if ["Error", "Warning"].include?(header) %>
        <svg class="h-6 w-6" viewBox="-2.4 -2.4 28.80 28.80" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="#000000">
          <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
          <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
          <g id="SVGRepo_iconCarrier">
            <path stroke="#ff4013" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v4m0 3v.01M5.313 20h13.374c1.505 0 2.471-1.6 1.77-2.931L13.77 4.363c-.75-1.425-2.79-1.425-3.54 0L3.543 17.068C2.842 18.4 3.808 20 5.313 20Z"></path>
          </g>
        </svg>
      <% else %>
        <svg
          class="h-6 w-6 text-green-400"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          aria-hidden="true"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
            />
        </svg>
      <% end %>


      <div class="ml-3 w-0 flex-1 pt-0.5">
        <p class="text-sm font-medium text-gray-900">
          <% if defined?(header) %>
            <%= header %>
          <% else %>
            Alert
          <% end %>
        </p>
        <p class="mt-1 text-sm text-gray-500">
          <% if defined?(message) %>
            <%= message %>
          <% end %>
        </p>
      </div>

      <div class="ml-4 flex-shrink-0 flex">
        <button
          data-action="notification#hide"
          class="bg-white rounded-md inline-flex text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-yellow-500"
        >
          <span class="sr-only">Close</span>
          <svg
            class="h-5 w-5"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 20 20"
            fill="currentColor"
            aria-hidden="true"
          >
            <path
              fill-rule="evenodd"
              d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
              clip-rule="evenodd"
              />
          </svg>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_pagination.html.erb
<div class="mt-6 sm:flex sm:items-center sm:justify-between ">
  <div class="text-sm text-gray-500 dark:text-gray-400">
    Page <span class="font-medium text-gray-700 dark:text-gray-100">1 of 10</span>
  </div>

  <div class="flex items-center mt-4 gap-x-4 sm:mt-0">
    <a href="#" class="flex items-center justify-center w-1/2 px-5 py-2 text-sm text-gray-700 capitalize transition-colors duration-200 bg-white border rounded-md sm:w-auto gap-x-2 hover:bg-gray-100 dark:bg-gray-900 dark:text-gray-200 dark:border-gray-700 dark:hover:bg-gray-800">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 rtl:-scale-x-100">
        <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 15.75L3 12m0 0l3.75-3.75M3 12h18"/>
      </svg>

      <span>
                    previous
                </span>
    </a>

    <a href="#" class="flex items-center justify-center w-1/2 px-5 py-2 text-sm text-gray-700 capitalize transition-colors duration-200 bg-white border rounded-md sm:w-auto gap-x-2 hover:bg-gray-100 dark:bg-gray-900 dark:text-gray-200 dark:border-gray-700 dark:hover:bg-gray-800">
                <span>
                    Next
                </span>

      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 rtl:-scale-x-100">
        <path stroke-linecap="round" stroke-linejoin="round" d="M17.25 8.25L21 12m0 0l-3.75 3.75M21 12H3"/>
      </svg>
    </a>
  </div>
</div>