config/routes.rb
require "sidekiq/web"
Sidekiq::Web.app_url = "/"

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  mount Sidekiq::Web => '/sidekiq'
  namespace :admin do
    get '/sign_in', to: "sign_ins#new", as: :admin_sign_in
    resource :sign_ins, only: [:create, :destroy]
    resources :product_urls, except: [:index]
  end

  authenticated :user do
    root 'product_urls#index', as: :user_root
  end
  root 'home#index'
  resources :home, only: [:show]
end

app/models/product_url.rb
class ProductUrl < ApplicationRecord
  belongs_to :partner
  belongs_to :creator, class_name: 'User', foreign_key: :creator_id, inverse_of: :product_urls
  validates :url, presence: true
  enum :scraping_status, [:pending, :processing, :success, :failed]
  enum :url_source, [:manual, :telegram], _prefix: true
  validates_presence_of :channel_name, if: Proc.new { |url| url.url_source == 'telegram' }
  has_many_attached :product_images
  after_create_commit :fetch!

  def time_taken_in_seconds
    return if scraping_ended_on.blank? || scraping_started_on.blank?
    scraping_ended_on.to_time.to_i - scraping_started_on.to_time.to_i
  end

  def fetch!(async = true)
    if async
      FetchProductUrlJob.perform_later(id)
    else
      FetchProductUrlJob.perform_now(id)
    end
  end
end

app/models/product_url/product.rb
class ProductUrl::Product
  attr_accessor :product_url

  def initialize(product_url)
    @product_url = product_url
  end

  def create_product!
    ApplicationRecord.transaction do
      find_or_create_category!
      source_data = product_url.parsed_data
      @product    = product_url.partner.products.find_or_create_by(pid: source_data['pid'], name: source_data['name'], description: source_data['description'].to_s)
      if @product.errors.none?
        meta_headers               = {}
        meta_headers[:title]       = source_data.dig('meta_title') if source_data.dig('meta_title').present?
        meta_headers[:description] = source_data.dig('meta_description') if source_data.dig('meta_description').present?
        meta_headers[:keywords]    = source_data.dig('meta_keywords') if source_data.dig('meta_keywords').present?
        @product.update(
          total_ratings:        source_data['total_ratings'].to_i,
          total_reviews:        source_data['total_reviews'].to_i,
          avg_rating:           source_data['avg_rating'].to_f,
          price:                source_data['price'].to_f,
          maximum_retail_price: source_data['maximum_retail_price'].to_f,
          offer_percentage:     source_data['offer_percentage'].to_f,
          meta_headers:         meta_headers,
          category_id:          @category&.id
        )
      end
    end
    attach_images!
  end

  private

  def find_or_create_category!
    @category = nil
  end

  def attach_images!
    return unless product_url.product_images.attached?
    product_url.product_images.each do |product_image|
      next if product_image.blob.blank?
      @product.images.attach(product_image.blob)
    end
  end
end

app/controllers/admin/product_urls_controller.rb
class Admin::ProductUrlsController < ApplicationController
  include Authentication
  before_action :set_product_url, only: [:show]

  def index
    @product_urls = current_user.product_urls.includes(:partner).order(created_at: :desc)
  end

  def new
    @product_url = current_user.product_urls.new
  end

  def create
    @product_url = ProductUrl.create(product_url_params.merge(creator_id: current_user.id))
    if @product_url.errors.none?
      flash[:success] = "The URL you've submitted being parsed, please wait for some time."
      redirect_to user_root_path
    end
  end

  def show

  end

  private

  def product_url_params
    params.require(:product_url).permit(:url, :partner_id)
  end

  def set_product_url
    @product_url = ProductUrl.find_by(id: params[:id])
    return if @product_url.present?
    flash[:error] = "Requested product URL not found."
    redirect_to admin_product_urls_path
  end
end

app/controllers/product_urls_controller.rb
class ProductUrlsController < ApplicationController
  before_action :set_product_url, only: [:show]

  def index
    @product_urls = current_user.product_urls.includes(:partner).order(created_at: :desc)
  end

  def new
    @product_url = current_user.product_urls.new
  end

  def create
    @product_url = ProductUrl.create(product_url_params.merge(creator_id: current_user.id))
    if @product_url.errors.none?
      flash[:success] = "The URL you've submitted being parsed, please wait for some time."
      redirect_to user_root_path
    end
  end

  def show

  end

  private

  def product_url_params
    params.require(:product_url).permit(:url, :partner_id)
  end

  def set_product_url
    @product_url = ProductUrl.find_by(id: params[:id])
    return if @product_url.present?
    flash[:error] = "Requested product URL not found."
    redirect_to product_urls_path
  end
end

app/helpers/product_urls_helper.rb
module ProductUrlsHelper
  def status_tag(status)
    case status
    when 'pending'
      'bg-yellow-100 text-yellow-700'
    when 'processing'
      'bg-blue-100 text-blue-700'
    when 'success'
      'bg-green-100 text-green-700'
    else
      'bg-red-100 text-red-700'
    end
  end
end

app/views/admin/product_urls/_form.html.erb
<!-- This is an example component -->
<%= form_with model: @product_url, class: 'flex items-center w-full' do |f| %>
  <div class="mx-auto w-full">
    <div class="flex items-center justify-center w-full  h-screen bg-red-100">
      <div class="bg-white rounded-2xl border shadow-x1 p-10 max-w-lg">
        <div class="flex flex-col items-center space-y-4">
          <h1 class="font-bold text-2xl text-gray-700 w-4/6 text-center">Product URL</h1>
          <p class="text-sm text-gray-500 text-center w-5/6">
            Hello, please enter your product URLs you want to be parsed
          </p>
          <%= f.text_field :url, class: 'border-2 rounded-lg w-full h-12 px-4', placeholder: 'Enter URL' %>
          <%= f.select :partner_id, options_for_select(Partner.all.pluck(:name, :id), nil), { prompt: 'Select Partner' }, { class: 'border-2 rounded-lg w-full h-12 px-4' } %>
          <%= f.submit 'Fetch', class: "bg-red-400 text-white rounded-md hover:bg-red-500 font-semibold px-4 py-3 w-full" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/product_urls/_product_url.html.erb
<tr>
  <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
    <div>
      <h2 class="font-medium text-gray-800 dark:text-white "><%= product_url.partner.name %></h2>
      <p class="text-sm font-normal text-gray-600 dark:text-gray-400">
        <span><%= product_url.url.truncate(3) %></span>
        <a href="<%= product_url.url %>" target="_blank">Show link</a>
      </p>
    </div>
  </td>

  <td class="px-12 py-4 text-sm font-medium whitespace-nowrap">
    <div class="inline px-3 py-1 text-sm font-normal rounded-full gap-x-2 bg-emerald-100/60 <%= status_tag(product_url.scraping_status) %>"><%= product_url.scraping_status.humanize %></div>
  </td>

  <td class="px-4 py-4 text-sm whitespace-nowrap">
    <div>
      <h4 class="text-gray-700 dark:text-gray-200 whitespace-nowrap overflow-hidden truncate max-w-xs" title="<%= product_url.parsed_data&.dig('name') || "Not fetched" %>"><%= product_url.parsed_data&.dig('name') || "Not fetched" %></h4>
    </div>
  </td>

  <td class="px-4 py-4 text-sm whitespace-nowrap">
    <div>
      <h4 class="text-gray-700 dark:text-gray-200"><%= product_url.failure_reason || "NA" %></h4>
    </div>
  </td>

  <td class="px-4 py-4 text-sm whitespace-nowrap">
    <div>
      <h4 class="text-gray-700 dark:text-gray-200"><%= product_url.time_taken_in_seconds.present? ? "#{product_url.time_taken_in_seconds} sec" : '-' %> </h4>
    </div>
  </td>

  <td class="px-4 py-4 text-sm whitespace-nowrap">
    <% if product_url.scraping_status == 'processing' %>
      <div class="animate-spin inline-block w-5 h-5 border-[3px] m-auto border-current border-t-transparent text-gray-800 rounded-full dark:text-white" role="status" aria-label="loading">
        <span class="sr-only">Loading...</span>
      </div>
    <% else %>
      <%= link_to product_url_path(product_url), class: "px-1 py-1 text-gray-500 transition-colors duration-200 rounded-lg dark:text-gray-300" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 12.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 18.75a.75.75 0 110-1.5.75.75 0 010 1.5z"/>
        </svg>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/admin/product_urls/index.html.erb
<section class="container px-4 mx-auto">
  <div class="sm:flex sm:items-center sm:justify-between">

    <div class="flex items-center mt-4 gap-x-3">
      <button class="flex items-center justify-center w-1/2 px-5 py-2 text-sm text-gray-700 transition-colors duration-200 bg-white border rounded-lg gap-x-2 sm:w-auto dark:hover:bg-gray-800 dark:bg-gray-900 hover:bg-gray-100 dark:text-gray-200 dark:border-gray-700">
        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
          <g clip-path="url(#clip0_3098_154395)">
            <path d="M13.3333 13.3332L9.99997 9.9999M9.99997 9.9999L6.66663 13.3332M9.99997 9.9999V17.4999M16.9916 15.3249C17.8044 14.8818 18.4465 14.1806 18.8165 13.3321C19.1866 12.4835 19.2635 11.5359 19.0351 10.6388C18.8068 9.7417 18.2862 8.94616 17.5555 8.37778C16.8248 7.80939 15.9257 7.50052 15 7.4999H13.95C13.6977 6.52427 13.2276 5.61852 12.5749 4.85073C11.9222 4.08295 11.104 3.47311 10.1817 3.06708C9.25943 2.66104 8.25709 2.46937 7.25006 2.50647C6.24304 2.54358 5.25752 2.80849 4.36761 3.28129C3.47771 3.7541 2.70656 4.42249 2.11215 5.23622C1.51774 6.04996 1.11554 6.98785 0.935783 7.9794C0.756025 8.97095 0.803388 9.99035 1.07431 10.961C1.34523 11.9316 1.83267 12.8281 2.49997 13.5832" stroke="currentColor" stroke-width="1.67" stroke-linecap="round" stroke-linejoin="round"/>
          </g>
          <defs>
            <clipPath id="clip0_3098_154395">
              <rect width="20" height="20" fill="white"/>
            </clipPath>
          </defs>
        </svg>
        <span>Upload</span>
      </button>

      <%= link_to new_product_url_path, class: "flex items-center justify-center w-1/2 px-5 py-2 text-sm tracking-wide text-white transition-colors duration-200 bg-blue-500 rounded-lg shrink-0 sm:w-auto gap-x-2 hover:bg-blue-600 dark:hover:bg-blue-500 dark:bg-blue-600" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"/>
        </svg>
        <span>Add new</span>
      <% end %>
    </div>
  </div>

  <div class="flex flex-col mt-6">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="overflow-hidden border border-gray-200 dark:border-gray-700 md:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
            <thead class="bg-gray-50 dark:bg-gray-800">
            <tr>
              <th scope="col" class="py-3.5 px-4 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">
                <button class="flex items-center gap-x-3 focus:outline-none">
                  <span>Partner</span>
                </button>
              </th>

              <th scope="col" class="px-12 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Status</th>
              <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">About</th>
              <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Failure
                reason (if any)
              </th>
              <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Time
                taken
              </th>
              <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">
                Details
              </th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200 dark:divide-gray-700 dark:bg-gray-900">
            <%= render partial: 'product_url', collection: @product_urls, as: :product_url %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</section>

app/views/admin/product_urls/new.html.erb
<!-- This is an example component -->
<%= form_with model: @product_url, class: 'flex items-center w-full' do |f| %>
  <div class="mx-auto w-full">
    <div class="flex items-center justify-center w-full  h-screen bg-red-100">
      <div class="bg-white rounded-2xl border shadow-x1 p-10 max-w-lg">
        <div class="flex flex-col items-center space-y-4">
          <h1 class="font-bold text-2xl text-gray-700 w-4/6 text-center">Product URL</h1>
          <p class="text-sm text-gray-500 text-center w-5/6">
            Hello, please enter your product URLs you want to be parsed
          </p>
          <%= f.text_field :url, class: 'border-2 rounded-lg w-full h-12 px-4', placeholder: 'Enter URL' %>
          <%= f.select :partner_id, options_for_select(Partner.all.pluck(:name, :id), nil), { prompt: 'Select Partner' }, { class: 'border-2 rounded-lg w-full h-12 px-4' } %>
          <%= f.submit 'Start', class: "bg-red-400 text-white rounded-md hover:bg-red-500 font-semibold px-4 py-3 w-full" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/product_urls/show.html.erb
<script src="https://cdn.tailwindcss.com"></script>
<script>
    tailwind.config = {
        theme: {
            extend: {
                animation: {
                    'spin-slow': 'spin 5s linear infinite',
                },
            },
        },
        plugins: [],
    }
</script>
<div class="flex m-auto items-center">
  <div class="group relative mx-auto w-full overflow-hidden rounded-[16px] bg-gray-300 p-[1px] transition-all duration-300 ease-in-out hover:bg-gradient-to-r hover:from-indigo-500 hover:via-purple-500 hover:to-pink-500">
    <div class="group-hover:animate-spin-slow invisible absolute -top-40 -bottom-40 left-10 right-10 bg-gradient-to-r from-transparent via-white/90 to-transparent group-hover:visible"></div>
    <div class="relative rounded-[15px] bg-white p-6">
      <div class="space-y-4">
        <% if @product_url.parsed_data.present? %>
          <% @product_url.parsed_data.each do |key, value| %>
            <p class="font-md text-slate-500">
              <b><%= key.humanize %></b>&nbsp;:&nbsp;<%= value.is_a?(Array) ? value.join(' > ') : value  %></p>
          <% end %>
          <% if @product_url.product_images.attached? %>
            <% @product_url.product_images.each_with_index do |product_image, index| %>
              <p class="font-bold">Image: <%= index + 1 %></p>
              <p><%= image_tag(rails_blob_path(product_image)) %></p>
            <% end %>

          <% end %>
        <% else %>
          <p class="text-lg font-semibold text-slate-800"> No parsed data found!</p>
        <% end %>
      </div>
    </div>
  </div>
</div>